POST http://localhost:3000/api/blogs
content-type: application/json
authorization: bearer TOKEN

{
    "author": "userwithemail",
    "url": "http://testbearer422.com/blog222",
    "title": "testbearer32",
    "likes": 242,
    "year": 2021
}

