POST http://localhost:3000/api/blogs
content-type: application/json
authorization: bearer TOKEN

{
    "author": "userwithemail",
    "url": "http://testbearer4.com/blog",
    "title": "testbearer3",
    "likes": 24,
    "year": 2021
}

